# sonic cisco one image installer

SONIC_ONE_IMAGE = sonic-cisco.bin
$(SONIC_ONE_IMAGE)_MACHINE = cisco
$(SONIC_ONE_IMAGE)_IMAGE_TYPE = onie
$(SONIC_ONE_IMAGE)_INSTALLS += $(SYSTEMD_SONIC_GENERATOR)
$(SONIC_ONE_IMAGE)_INSTALLS += $(LEABA_SDK_KMOD_SRC)

$(SONIC_ONE_IMAGE)_DOCKERS += $(SONIC_INSTALL_DOCKER_IMAGES)
SONIC_INSTALLERS += $(SONIC_ONE_IMAGE)
