# sonic platform package

SONIC_PLATFORM_VERSION = 1.0
SONIC_PLATFORM_NAME = sonic_platform
export SONIC_PLATFORM_PY3 = $(SONIC_PLATFORM_NAME)-$(SONIC_PLATFORM_VERSION)-py3-none-any.whl

$(SONIC_PLATFORM_PY3)_SRC_PATH = $(PLATFORM_PATH)/sonic_platform
$(SONIC_PLATFORM_PY3)_PYTHON_VERSION = 3
$(SONIC_PLATFORM_PY3)_NAME = $(SONIC_PLATFORM_NAME)
$(SONIC_PLATFORM_PY3)_VERSION = $(SONIC_PLATFORM_VERSION)
$(SONIC_PLATFORM_PY3)_TEST = n

SONIC_PYTHON_WHEELS += $(SONIC_PLATFORM_PY3)
